% 
% BDP BrainSuite Diffusion Pipeline
% 
% Copyright (C) 2018 The Regents of the University of California and
% the University of Southern California
% 
% Created by Chitresh Bhushan, Divya Varadarajan, Justin P. Haldar, Anand A. Joshi,
%            David W. Shattuck, and Richard M. Leahy
% 
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public License
% as published by the Free Software Foundation; version 2.
% 
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
% USA.
% 


function bdp_create_shell_script(filename, manifestFile)
% Creates the bdp.sh shell-script to run BDP. 
% bdp.sh is the custom shell-script, which should be used by user. 
% This function is called by CompileBrainSuiteDiffusionPipeline() during building BDP. 

if nargin == 1
    manifestFile = 'bdpmanifest.xml';
end

matlab_info = ver('MATLAB');
matlabReleaseStr = strrep(matlab_info.Release, '(', '');
matlabReleaseStr = strrep(matlabReleaseStr, ')', '');

[mcrMajor, mcrMinor, mcrUpdate] = mcrversion();
mcrVersionDotStr = [num2str(mcrMajor) '.' num2str(mcrMinor)];
mcrVersionStr = [num2str(mcrMajor) num2str(mcrMinor)];
if mcrUpdate > 0
    mcrVersionDotStr = [mcrVersionDotStr '.' num2str(mcrUpdate)];
    mcrVersionStr = [mcrVersionStr mcrUpdate];
end

switch matlabReleaseStr
    case 'R2015b'
        MCR_root_name = 'MATLAB_Runtime';
        
    case 'R2012a'
        MCR_root_name = 'MATLAB_Compiler_Runtime';
        
    otherwise
        error('Shell-script creation is not supported on this Matlab release: %s\n', matlabReleaseStr)
end


if ismac
    MCR_DIR   = ['/Applications/MATLAB/' MCR_root_name '/v' mcrVersionStr];
    MATLABDIR = ['/Applications/MATLAB_' matlabReleaseStr '.app'];
    PATH = [...
        'DYLD_LIBRARY_PATH=.:${BrainSuiteMCR}/runtime/maci64 ;\n'...
        'DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:${BrainSuiteMCR}/bin/maci64 ;\n'...
        'DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:${BrainSuiteMCR}/sys/os/maci64;\n'...
        'XAPPLRESDIR=${BrainSuiteMCR}/X11/app-defaults ;\n'...
        'export DYLD_LIBRARY_PATH;\n'...
        'export XAPPLRESDIR;\n'];
    TESTMCR = sprintf('if [ ! -e ${BrainSuiteMCR}/runtime/maci64/libmwmclmcrrt.%s.dylib ]', mcrVersionDotStr);
    lib_Ext = '.dylib';
    RUNCOMMAND = '${exe_dir}/bdp.app/Contents/MacOS/BrainSuite_Diffusion_pipeline $args';

else
    MCR_DIR   = ['/usr/local/MATLAB/' MCR_root_name '/v' mcrVersionStr];
    MATLABDIR = ['/usr/local/MATLAB/' matlabReleaseStr];
    PATH = [...
        'LD_LIBRARY_PATH=.:${BrainSuiteMCR}/runtime/glnxa64 ;\n'...
        'LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${BrainSuiteMCR}/bin/glnxa64 ;\n'...
        'LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${BrainSuiteMCR}/sys/os/glnxa64;\n'...
        'MCRJRE=${BrainSuiteMCR}/sys/java/jre/glnxa64/jre/lib/amd64 ;\n'...
        'LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE}/native_threads ; \n'...
        'LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE}/server ;\n'...
        'LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE}/client ;\n'...
        'LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MCRJRE} ;  \n'...
        'XAPPLRESDIR=${BrainSuiteMCR}/X11/app-defaults ;\n'...
        'export LD_LIBRARY_PATH;\n'...
        'export XAPPLRESDIR;\n'];
    TESTMCR = sprintf('if [ ! -e ${BrainSuiteMCR}/runtime/glnxa64/libmwmclmcrrt.so.%s ]', mcrVersionDotStr);
    lib_Ext = '';
    RUNCOMMAND = '${exe_dir}/bdp $args';
end


usageMsg = bdp_usage(true, manifestFile);
MCR_version_text = sprintf('%s (%s)', matlabReleaseStr, mcrVersionDotStr);

script = sprintf([...
    '#!/bin/bash\n'...
    '\n'...
    'exe_name=$0\n'...
    'exe_dir=`dirname "$0"`\n'...
    '\n'...
    '# If MCR %s is installed in a non-default location, define correct path \n'... MCR_version_text
    '# on next line and uncomment it (remove the leading "#")\n'...
    '#BrainSuiteMCR="/path/to/your/MCR";\n'...
    '\n'...
    'if [ -z "$BrainSuiteMCR" ]; then\n'...
    '  if [ -e %s ]; then\n'... MCR_DIR
    '    BrainSuiteMCR="%s";\n'... MCR_DIR
    '  elif [ -e %s/runtime ]; then\n'... MATLABDIR
    '    BrainSuiteMCR="%s";\n'... MATLABDIR
    '    echo\n'...
    '    echo "Located Matlab installation with runtime directory."\n'...
    '    echo\n'...
    '  else\n'...
    '    echo\n'...
    '    echo "BDP could not locate an installation of MCR %s on this system."\n'... MCR_version_text
    '    echo \n'...
    '    echo "Please install the Matlab MCR %s from MathWorks website at:"\n'... MCR_version_text
    '    echo\n'...
    '    echo "http://www.mathworks.com/products/compiler/mcr/"\n'...
    '    echo \n'...
    '    echo "If you already have MCR %s [or Matlab %s with the Matlab Compiler]"\n'... MCR_version_text, matlabReleaseStr
    '    echo "installed, please edit ${exe_name} by uncommenting and editing"\n'...
    '    echo "the following line near the top of the file:"\n'...
    '    echo\n'...
    '    echo "#BrainSuiteMCR=\\\\"/path/to/your/MCR\\\\";"\n'...
    '    echo\n'...
    '    echo "(replace /path/to/your/MCR with the path to your MCR [or Matlab] installation)"\n'...
    '    echo\n'...
    '    exit 78\n'...
    '  fi\n'...
    'fi\n'...
    '\n'...
    '%s; then\n' ... TESTMCR
    '  echo\n'...
    '  echo "BDP Could not find a valid installation of MCR %s [or Matlab %s with Matlab Compiler] at following location:"\n'... MCR_version_text, matlabReleaseStr
    '  echo ${BrainSuiteMCR}\n'...
    '  echo\n'...
    '  echo "Could not find following file, which must be present for a valid installation:"\n'...
    '  echo ${BrainSuiteMCR}/runtime/glnxa64/libmwmclmcrrt.so.%s%s\n'... mcrVersionDotStr, lib_Ext
    '  echo\n'...
    '  echo "Please install the Matlab MCR %s from MathWorks at:"\n'... MCR_version_text
    '  echo "     http://www.mathworks.com/products/compiler/mcr/"\n'...
    '  echo \n'...
    '  echo "If you already have MCR %s [or Matlab %s with Matlab Compiler]"\n'... MCR_version_text, matlabReleaseStr
    '  echo "installed, please edit ${exe_name} by uncommenting and editing"\n'...
    '  echo "the following line near the top of the file:"\n'...
    '  echo\n'...
    '  echo "#BrainSuiteMCR=\\\\"/path/to/your/MCR\\\\";"\n'...
    '  echo\n'...
    '  echo "(replace /path/to/your/MCR with the path to your MCR [or Matlab] installation)"\n'...
    '  echo\n'...
    '  echo "NOTE: THE EXACT VERSION NUMBER IS IMPORTANT. NEWER VERSIONS WILL NOT WORK."\n'...
    '  exit 78\n'...
    'fi\n'...
    '\n'...
    'read -d '''' usage <<EOF\n'...
    '\n'...
    '%s'... usageMsg
    '\n'...
    'EOF\n'...
    '\n'...
    '# Parse inputs\n'...
    'if [ $# -lt 1 ]; then\n'...
    '  echo\n'...
    '  echo "$usage"\n'...
    '  echo\n'...
    '  exit\n'...
    'fi\n'...
    '\n'...
    'while [ $# -gt 0 ]; do\n'...
    '  token=`echo "$1" | sed ''s/ /\\\\\\\\\\\\\\\\ /g''`   # Add blackslash before each blank\n'...
    '  args="${args} ${token}" \n'...
    '  shift\n'...
    'done\n'...
    '\n'...
    '# Set up path for MCR applications.\n'...
    '%s\n'... PATH
    '\n' ...
    'BDPEXEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)" ;\n'...
    'export BDPEXEDIR;\n'...
    '\n'...
    '%s\n'... RUNCOMMAND
    '\n'...
    'exit\n'], MCR_version_text, MCR_DIR, MCR_DIR, MATLABDIR, MATLABDIR, ...
    MCR_version_text, MCR_version_text, MCR_version_text, matlabReleaseStr, ...
    TESTMCR, ...
    MCR_version_text, matlabReleaseStr, mcrVersionDotStr, lib_Ext, MCR_version_text, MCR_version_text, matlabReleaseStr, ...
    usageMsg, PATH, RUNCOMMAND);


try
    fid = fopen(filename, 'w');
catch err
    error('BDP:PackageError', 'Could not create shell script');
end

fprintf(fid, script);
fclose(fid);
