name: Build BDP on GitHub Runner
run-name: Build BDP by @${{ github.actor }}

on: [workflow_dispatch, push]
env:
  DEV_VERSION: 26a_dev
  REF_NAME: ${{ github.ref_name }}  
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_TOKEN }}
  
jobs:
  build:
    permissions: write-all
    name: Build BDP on GitHub Runner
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            enable_cache: true
          - os: windows-latest
            enable_cache: true
          - os: macos-26
            enable_cache: false
          - os: macos-26-intel
            enable_cache: true

    runs-on:
      labels: ["${{ matrix.os }}" ]

    steps:
      - name: Going out to clean
        if: runner.os == 'Linux'
        run: |
          echo "Before cleanup:"
          df -h
          # Delete massive pre-installed software directories
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          echo "After cleanup:"
          df -h

      - name: Set release version
        if: github.event_name == 'release'
        shell: bash
        run:
          echo "VERSION=${REF_NAME#v}" >> $GITHUB_ENV

      - name: Set dev version
        if: github.event_name != 'release'
        shell: bash
        run:
          echo "VERSION=${DEV_VERSION#v}" >> $GITHUB_ENV


      - name: Set Global Build Identifier
        shell: bash
        run: |
          LOCAL_SHA=${GITHUB_SHA::7}        
          echo "SHORT_SHA=${LOCAL_SHA}" >> $GITHUB_ENV
          echo "BUILD_STR=bdp_${{ env.VERSION }}_build_${LOCAL_SHA}" >> $GITHUB_ENV

      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          release: R2025b
          cache: ${{ matrix.enable_cache }}
          products: >
            MATLAB_Compiler
            Image_Processing_Toolbox
            Medical_Imaging_Toolbox
            Parallel_Computing_Toolbox

      - name: set MacOS x64 environment variables
        if: runner.os == 'macOS' && runner.arch == 'X64'
        run: |
          echo "Package=${PWD}/packaging_tools/${{ env.BUILD_STR }}_maci64.tar.gz" >> $GITHUB_ENV

      - name: set MacOS x64 environment variables
        if: runner.os == 'macOS' && runner.arch == 'ARM64'
        run: |
          echo "Package=${PWD}/packaging_tools/${{ env.BUILD_STR }}_maca64.tar.gz" >> $GITHUB_ENV

      - name: set Linux environment variables
        if: runner.os == 'Linux'
        run: |
          echo "Package=${PWD}/packaging_tools/${{ env.BUILD_STR }}_linux.tar.gz" >> $GITHUB_ENV

      - name: set Windows environment variables
        if: runner.os == 'Windows'
        run: |
          echo "Package=${PWD}/packaging_tools/${{ env.BUILD_STR }}_win64.zip" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Prepare for Artifact
        if: github.event_name != 'release'
        shell: bash
        run:
          BASENAME=$(basename "$PACKAGE_PATH")
          echo $BASENAME
          echo "ARTIFACT_NAME=$BASENAME" >> $GITHUB_ENV
          
      - name: compile BDP Mex files
        uses: matlab-actions/run-command@v3
        with:
          startup-options: -sd packaging_tools
          command: CompileBDPMexFiles
          
      - name: compile BDP
        uses: matlab-actions/run-command@v3
        with:
          startup-options: -sd packaging_tools
          command: "CompileBrainSuiteDiffusionPipeline --package ${{ env.VERSION }} --build ${{ env.SHORT_SHA }} --lic GPL"

      - name: Prepare for Artifact
        if: github.event_name != 'release'
        shell: bash
        run:
          BASENAME=$(basename "$PACKAGE_PATH")
          echo "ARTIFACT_NAME=$BASENAME" >> $GITHUB_ENV

      - name: Save Build as Artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT_NAME }}
          # path: buildGUI/DRViewer 
          path: ${{ env.Package }}
          overwrite: true
          
      - name: Publish ${{ env.Package }}
        if: github.event_name == 'release'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.Package }}"
          tag: ${{ env.VERSION }}        
          allowUpdates: true
